### ISSUE TITLE
Is this usable/hosted anywhere?

### ISSUE THREAD

**Issue by cpjolicoeur** [NBA-Betting/NBA_Betting#1]
Just curious the status of this project as I see it's actively developed.  Is this active anywhere that I could get a peek at, or do you have any terraform or infrastructure docs available that I could use to mimic your AWS layout myself and run on my own?

**Comment by dbonanWoobler** [comment]
same question here, i have developed many visualizations of player props projections and usage. I'd be curious to plug this one to my viz

**Comment by JimCollinsDC** [comment]
Same as above

**Comment by treezie** [comment]
Same question.

**Comment by JimCollinsDC** [comment]
It's available here: https://colab.research.google.com/drive/1DbPgAVf0D_Q_bmYM20R5zxgKsqftWjgt?usp=sharing#scrollTo=zWnXvIaEybeu courtesy of Siraj Raval

Check out Siraj Raval's excellent video also! https://www.youtube.com/watch?v=IDthta5sUGQ&t=118s

**Comment by jeffjohannsen** [comment]
I am working on making the web app publically available and should be able to do that in a couple of weeks. The predictive performance of the current setup is not special at the moment so I am working on improving that more so than providing it publically at this time.

The infrastructure is pretty simple. Cron jobs on AWS EC2 to load and process data. PostgreSQL RDS on AWS to store it. the job scheduling markdown file in docs shows the general Cron setup. I'll add the RDS outline in there soon.

**Comment by treezie** [comment]
> I am working on making the web app publically available and should be able to do that in a couple of weeks. The predictive performance of the current setup is not special at the moment so I am working on improving that more so than providing it publically at this time.
> 
> The infrastructure is pretty simple. Cron jobs on AWS EC2 to load and process data. PostgreSQL RDS on AWS to store it. the job scheduling markdown file in docs shows the general Cron setup. I'll add the RDS outline in there soon.

Thank you, this seems like a very comprehensive project. I appreciate your work!

**Comment by KnightRider37** [comment]
Will this be usable for the new NBA season 23-24? Thanks

**Comment by Kishore-S-2410** [comment]
How to run this

**Comment by cpjolicoeur** [comment]
@Kishore-S-2410 Please read the README file in the repository.  All the information you need is there.

**Comment by Kishore-S-2410** [comment]
No bro it's like i have to run the repository to do a documentation as a
task from a company so can you give me details of which files and order to
run to get outputs without any error

**Comment by jeffjohannsen** [comment]
@Kishore-S-2410
This project isn't really a specific set of code to be run in order to get a specific outcome. It is more of an outline, action plan, and storage space for approaching the difficult problem of predicting the outcomes of NBA games. That being said I have done a poor job of explaining the pieces and steps of this project, along with how they fit together. Most of my time has been spent trying to see if I could get some positive results out of it and much less time has been spent on making it easy to understand. I am working on fixing that problem to some degree and should have the beginnings of useful documentation out in the next couple of weeks. 

Until recently I was hosting a web app and dashboard at [nba-betting.us](https://nba-betting.us) but with the model predictions currently being mediocre, I don't think that is worth the time/money at this moment. Instead, I am in the process of switching that domain over to a GitHub pages site that does a better job of explaining the project than the current Readme does. This will also show up by the end of November.

**Comment by Kishore-S-2410** [comment]
Yeah thanks for the update and i kind of interested in this project, it
will be appreciated if you can explain me or share me some more knowledge
on this. I really like this one, Good job so far man
